const users = [
  {
    id: 1,
    username: "João Silva",
    photoUrl: "https://as2.ftcdn.net/v2/jpg/03/41/82/11/1000_F_341821142_nequVUxpwzj5riEeiCA9jDmsY4OqqDLT.jpg",
    status: "Online",
    lastMessage: "Oi, como você está?",
    hasNewMessages: true,
  },
  {
    id: 2,
    username: "Maria Souza",
    photoUrl: "https://conteudo.imguol.com.br/c/entretenimento/46/2022/11/16/selfie-e-tambem-uma-maneira-de-autoconhecimento-diz-a-fotograda-maria-emilia-dinat-1668626272172_v2_1x1.jpg",
    status: "Ausente",
    lastMessage: "Estou bem, e você?",
    hasNewMessages: false,
  },
  {
    id: 3,
    username: "Carlos Oliveira",
    photoUrl: "https://i.pinimg.com/550x/6e/18/13/6e181304ec6ed08568238b9c2f83dc7d.jpg",
    status: "Offline",
    lastMessage: "Sem problemas, eu entendo.",
    hasNewMessages: true,
  },
  {
    id: 4,
    username: "Laura Santos",
    photoUrl: "https://static1.fiquediva.com.br/articles/3/36/63/@/48178-se-voce-quer-arrasar-no-fotao-e-ganhar-m-article_gallery_portrait-3.jpg",
    status: "Online",
    lastMessage: "Olá, prazer em te conhecer!",
    hasNewMessages: false,
  },
  {
    id: 5,
    username: "Pedro Almeida",
    photoUrl: "https://math.utsa.edu/wp-content/uploads/2021/03/Selfie-1-scaled.jpeg",
    status: "Ausente",
    lastMessage: "Como está sendo seu dia?",
    hasNewMessages: true,
  },
  {
    id: 6,
    username: "Mariana Costa",
    photoUrl: "https://i0.wp.com/emotioncard.com.br/wp-content/uploads/2017/07/Selfie-angulo.jpg?resize=500%2C500&ssl=1",
    status: "Online",
    lastMessage: "O que você está fazendo?",
    hasNewMessages: true,
  },
  {
    id: 7,
    username: "Daniel Pereira",
    photoUrl: "https://dt66ikht21gkc.cloudfront.net/img/selfie/502.jpg",
    status: "Offline",
    lastMessage: "Conversamos depois.",
    hasNewMessages: false,
  },
  {
    id: 8,
    username: "Sophia Santos",
    photoUrl: "https://assets-global.website-files.com/6268ee704c062ad6dcc39250/628492fbc1f1c7327c03212e_how-to-take-a-good-selfie-woman-outdoors.png",
    status: "Ausente",
    lastMessage: "Tenha um ótimo dia!",
    hasNewMessages: true,
  },
  {
    id: 9,
    username: "Gabriel Lima",
    photoUrl: "https://selfieblog.net/wp-content/uploads/2015/01/selfie-significado.jpg",
    status: "Online",
    lastMessage: "Vamos conversar em breve.",
    hasNewMessages: true,
  },
  {
    id: 10,
    username: "Isabella Fernandes",
    photoUrl: "https://blog.pajaris.com.br/wp-content/uploads/2021/02/poses-para-selfie-3.jpg",
    status: "Ausente",
    lastMessage: "Como foi seu fim de semana?",
    hasNewMessages: false,
  },
];

export default users;
